version: '2'
services:
  php:
    build: .
    links:
      - mysql
      - rabbitmq
    volumes:
      - .:/app
  mysql:
    image: mysql:5.7
    ports:
      - 127.0.0.2:3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: subscribe
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  rabbitmq:
    image: rabbitmq
    command: rabbitmq-server
    expose:
      - "5672"
      - "15672"